package com.longhuynh.jobhunt_backend.entity;

public enum ActionType {
    MEMBER_CREATED,
    JOB_CREATED,
    ACTIVITY_CREATED,
    JOB_UPDATED,
    JOB_MOVED,
    JOB_DELETED,
    NOTE_CREATED,
    ACTIVITY_UPDATED,
    DOCUMENT_CREATED,
    DOCUMENT_UPDATED,
    ACTIVITY_DELETED,
    CANDIDATE_CREATED,
    CANDIDATE_UPDATED,
}
